### ISSUE TITLE
after logout redirect to landing page

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-portal-frontend#43]
![image](https://github.com/SpatialDays/stac-portal-frontend/assets/17437897/69591538-a30d-48d6-b6ed-d7e9223dd0d3)

logout redirect can be changed as described here: https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-customize-sign-in-out

**Comment by mountaincharlie** [comment]
Different window.location.href options ive tried:

- window.location.href = '/.auth/logout?post_logout_redirect_uri={encoded_url_for_landing_page}'
    - This changes the redirect uri for some reason, taking the user to: https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/logout?post_logout_redirect_uri={encoded_url_for_**frontend**_page}

- window.location.href = 'https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/logout?post_logout_redirect_uri={encoded_url_for_landing_page}'
    - This prompts the user for which account to sign out and then redirects to: https://login.microsoftonline.com/283d3ef6-d421-48c6-ad4c-ba01a1999719/oauth2/v2.0/logoutsession
    - And displays the message: You've signed out of your account. It's a good idea to close all browser windows.

- window.location.href = 'https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri={encoded_url_for_landing_page}'
    - just takes the user straight to: https://login.microsoftonline.com/common/oauth2/v2.0/logoutsession

According to [these docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request) in order to use **post_logout_redirect_uri** "This URL must match one of the redirect URIs registered for your application in the app registration portal."
So we have added the landing page url to the appropriate place in the azure portal, but none of the above methods work still.

Possibly we can try putting the encoded version of the landing page url into the azure portal, or it may need time for those settings to take affect.

**Comment by james-hinton** [comment]
`az webapp auth update --name <app_name> --resource-group <group_name> --allowed-external-redirect-urls "https://myexternalurl.com"`

**Comment by mountaincharlie** [comment]
This should work now:
window.location.href = 'https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri={encoded_url_for_landing_page}'

Using the url format recommended [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request)

I will apply it and test it out on monday to make sure that its all secure etc, before pushing the changes.

**Comment by mountaincharlie** [comment]
> This should work now: window.location.href = '[https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri={encoded_url_for_landing_page}](https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri=%7Bencoded_url_for_landing_page%7D)'
> 
> Using the url format recommended [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request)
> 
> I will apply it and test it out on monday to make sure that its all secure etc, before pushing the changes.

Not sure if this is logging the user out, but im having trouble making a get or post request to /.auth/logout work so that the user is only redirected with window.location.href = process.env.REACT_APP_LOGOUT_REDIRECT_URL; once they have definitely been logged out.

I tried creating an event listener to listen for when the user is redirected to the AAD's logout/complete url, but this obviously doesnt work as the listener is no longer active once the user is redirected to that point.

The tempory fix is to use:
window.location.href = `/.auth/logout?post_logout_redirect_uri=${encodeURIComponent(process.env.REACT_APP_LOGOUT_REDIRECT_URL)}`
Which does logout the user, but redirects to AAD's own kind of lame logout complete page.

I will commit and push that for now, but will need to come back to this later

**Comment by james-hinton** [comment]
Not possible due to Azure bug
